base: 'http://anna-todo.ddev.site/'
baseVariants:
  -
    base: anna-todo.ddev.site
    condition: 'applicationContext == "Development"'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: Todo
